/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:d73575a7-00ac-4220-9ecd-dbe9db444170",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_vECMGrKlQ",
    "aws_user_pools_web_client_id": "5qr9kkrf2b9n1ibrbepnuq89rv",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://t5uylyxzkzbyfhahtvbbtz2mlm.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-x7nvewqhsrbjde25kl3lnug3vi",
    "aws_user_files_s3_bucket": "amplifyappimagestorage162241-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
